version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: tasks-platform-redis
    ports:
      - "6379:6379"
    networks:
      - tasks-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: tasks-platform-app
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=8080
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - tasks-network

networks:
  tasks-network:
    driver: bridge
